spring:
  application:
    name:
      nemo_board
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/board
    username: sa
    password:
